wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.15.9
    framework: huggingface
    huggingface_version: 4.31.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1703185704.471769
    t:
      1:
      - 1
      - 11
      - 12
      - 30
      - 49
      - 51
      - 55
      2:
      - 1
      - 11
      - 12
      - 30
      - 49
      - 51
      - 55
      3:
      - 23
      4: 3.11.4
      5: 0.15.9
      6: 4.31.0
      8:
      - 4
      - 5
